kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: echo
  namespace: pipeline-argocd
  labels:
    app: echo
    app.kubernetes.io/component: echo
    app.kubernetes.io/instance: echo
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - echo
        from:
          kind: ImageStreamTag
          namespace: pipeline-argocd
          name: 'echo:latest'
        lastTriggeredImage: >-
          image-registry.openshift-image-registry.svc:5000/pipeline-argocd/echo:latest
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    deploymentconfig: echo
  template:
    metadata:
      creationTimestamp: null
      labels:
        deploymentconfig: echo
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: echo
          image: >-
            image-registry.openshift-image-registry.svc:5000/pipeline-argocd/echo:latest
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
